# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RealEstatePriceEstimator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1716, 1025)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -70, 1741, 1091))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"background-color: rgb(239, 239, 239);\n"
"}\n"
"QVBoxLayout{\n"
"background-color: rgb(143, 143, 143);\n"
"\n"
"}\n"
"\n"
"QLineEdit, QComboBox\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 251, 771))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l0 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l0.setObjectName("l0")
        self.verticalLayout_2.addWidget(self.l0)
        self.i0_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.i0_2.setFont(font)
        self.i0_2.setStyleSheet("")
        self.i0_2.setMaxLength(12)
        self.i0_2.setObjectName("i0_2")
        self.verticalLayout_2.addWidget(self.i0_2)
        self.l1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l1.setStyleSheet("")
        self.l1.setObjectName("l1")
        self.verticalLayout_2.addWidget(self.l1)
        self.i1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i1.setObjectName("i1")
        self.verticalLayout_2.addWidget(self.i1)
        self.l2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l2.setObjectName("l2")
        self.verticalLayout_2.addWidget(self.l2)
        self.i2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i2.setObjectName("i2")
        self.verticalLayout_2.addWidget(self.i2)
        self.l3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l3.setObjectName("l3")
        self.verticalLayout_2.addWidget(self.l3)
        self.i3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i3.setObjectName("i3")
        self.verticalLayout_2.addWidget(self.i3)
        self.l4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l4.setObjectName("l4")
        self.verticalLayout_2.addWidget(self.l4)
        self.i4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i4.setObjectName("i4")
        self.verticalLayout_2.addWidget(self.i4)
        self.l5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l5.setObjectName("l5")
        self.verticalLayout_2.addWidget(self.l5)
        self.i5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i5.setObjectName("i5")
        self.verticalLayout_2.addWidget(self.i5)
        self.l6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l6.setObjectName("l6")
        self.verticalLayout_2.addWidget(self.l6)
        self.i6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i6.setObjectName("i6")
        self.verticalLayout_2.addWidget(self.i6)
        self.l7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l7.setObjectName("l7")
        self.verticalLayout_2.addWidget(self.l7)
        self.i7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i7.setObjectName("i7")
        self.verticalLayout_2.addWidget(self.i7)
        self.l8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l8.setObjectName("l8")
        self.verticalLayout_2.addWidget(self.l8)
        self.i8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i8.setObjectName("i8")
        self.verticalLayout_2.addWidget(self.i8)
        self.l9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l9.setObjectName("l9")
        self.verticalLayout_2.addWidget(self.l9)
        self.i9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i9.setObjectName("i9")
        self.verticalLayout_2.addWidget(self.i9)
        self.l10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l10.setObjectName("l10")
        self.verticalLayout_2.addWidget(self.l10)
        self.i10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i10.setObjectName("i10")
        self.verticalLayout_2.addWidget(self.i10)
        self.l11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l11.setObjectName("l11")
        self.verticalLayout_2.addWidget(self.l11)
        self.i11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i11.setObjectName("i11")
        self.verticalLayout_2.addWidget(self.i11)
        self.l12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l12.setObjectName("l12")
        self.verticalLayout_2.addWidget(self.l12)
        self.i12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i12.setObjectName("i12")
        self.verticalLayout_2.addWidget(self.i12)
        self.l13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l13.setObjectName("l13")
        self.verticalLayout_2.addWidget(self.l13)
        self.i13 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i13.setObjectName("i13")
        self.verticalLayout_2.addWidget(self.i13)
        self.predict = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.predict.setObjectName("predict")
        self.verticalLayout_2.addWidget(self.predict)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(290, 40, 1321, 591))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = MplWidget(self.horizontalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4.addWidget(self.widget)
        self.widget_2 = MplWidget(self.horizontalLayoutWidget_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 990, 251, 32))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.load = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.load.setObjectName("load")
        self.horizontalLayout_6.addWidget(self.load)
        self.dele = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.dele.setObjectName("dele")
        self.horizontalLayout_6.addWidget(self.dele)
        self.widget_3 = MplWidget(self.frame)
        self.widget_3.setGeometry(QtCore.QRect(270, 550, 1381, 541))
        self.widget_3.setObjectName("widget_3")
        self.selectFeature = QtWidgets.QComboBox(self.widget_3)
        self.selectFeature.setGeometry(QtCore.QRect(180, 50, 221, 21))
        self.selectFeature.setObjectName("selectFeature")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 890, 121, 21))
        self.label.setStyleSheet("font: 15pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.prediction = QtWidgets.QLabel(self.frame)
        self.prediction.setGeometry(QtCore.QRect(140, 890, 111, 21))
        self.prediction.setStyleSheet("font: 15pt \".AppleSystemUIFont\";")
        self.prediction.setObjectName("prediction")
        self.savedHouses = QtWidgets.QComboBox(self.frame)
        self.savedHouses.setGeometry(QtCore.QRect(20, 960, 251, 21))
        self.savedHouses.setObjectName("savedHouses")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 930, 239, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l0.setText(_translate("MainWindow", "Enter a unique Identidier"))
        self.i0_2.setText(_translate("MainWindow", "average"))
        self.l1.setText(_translate("MainWindow", "Rate of Policing"))
        self.i1.setText(_translate("MainWindow", "3.613524"))
        self.l2.setText(_translate("MainWindow", "Land Zoned for Lots over 25,000 sq.ft"))
        self.i2.setText(_translate("MainWindow", "11.363636"))
        self.l3.setText(_translate("MainWindow", "Proportion of Non-Retail Business"))
        self.i3.setText(_translate("MainWindow", "11.136779"))
        self.l4.setText(_translate("MainWindow", "Charles River (1 or 0)"))
        self.i4.setText(_translate("MainWindow", "0.069170    "))
        self.l5.setText(_translate("MainWindow", "Nitric oxide Concentration"))
        self.i5.setText(_translate("MainWindow", "0.554695    "))
        self.l6.setText(_translate("MainWindow", "Number of Rooms"))
        self.i6.setText(_translate("MainWindow", "6.284634    "))
        self.l7.setText(_translate("MainWindow", "Age of House"))
        self.i7.setText(_translate("MainWindow", "68.574901"))
        self.l8.setText(_translate("MainWindow", "distances to employment centres"))
        self.i8.setText(_translate("MainWindow", "3.795043    "))
        self.l9.setText(_translate("MainWindow", "Index of Accessibility to Highways"))
        self.i9.setText(_translate("MainWindow", "9.549407    "))
        self.l10.setText(_translate("MainWindow", "Property-Tax Rate Per $10,000"))
        self.i10.setText(_translate("MainWindow", "408.237154    "))
        self.l11.setText(_translate("MainWindow", "pupil-Teacher Ratio by Town"))
        self.i11.setText(_translate("MainWindow", "18.455534"))
        self.l12.setText(_translate("MainWindow", "1000(Bk - 0.63)^2"))
        self.i12.setText(_translate("MainWindow", "356.674032    "))
        self.l13.setText(_translate("MainWindow", "% lower status of the population"))
        self.i13.setText(_translate("MainWindow", "12.653063 "))
        self.predict.setText(_translate("MainWindow", "Predict Price"))
        self.load.setText(_translate("MainWindow", "Load Data"))
        self.dele.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Predicted Price $"))
        self.prediction.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Saved House Predictions"))

from mplwidget import MplWidget
