# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RealEstatePriceEstimator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1700, 1070)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, -30, 1661, 1061))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 241, 861))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l0 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l0.setObjectName("l0")
        self.verticalLayout_2.addWidget(self.l0)
        self.i0_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.i0_2.setFont(font)
        self.i0_2.setText("")
        self.i0_2.setMaxLength(12)
        self.i0_2.setObjectName("i0_2")
        self.verticalLayout_2.addWidget(self.i0_2)
        self.l1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l1.setObjectName("l1")
        self.verticalLayout_2.addWidget(self.l1)
        self.i1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i1.setText("")
        self.i1.setObjectName("i1")
        self.verticalLayout_2.addWidget(self.i1)
        self.l2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l2.setObjectName("l2")
        self.verticalLayout_2.addWidget(self.l2)
        self.i2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i2.setText("")
        self.i2.setObjectName("i2")
        self.verticalLayout_2.addWidget(self.i2)
        self.l3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l3.setObjectName("l3")
        self.verticalLayout_2.addWidget(self.l3)
        self.i3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i3.setText("")
        self.i3.setObjectName("i3")
        self.verticalLayout_2.addWidget(self.i3)
        self.l4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l4.setObjectName("l4")
        self.verticalLayout_2.addWidget(self.l4)
        self.i4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i4.setText("")
        self.i4.setObjectName("i4")
        self.verticalLayout_2.addWidget(self.i4)
        self.l5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l5.setObjectName("l5")
        self.verticalLayout_2.addWidget(self.l5)
        self.i5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i5.setText("")
        self.i5.setObjectName("i5")
        self.verticalLayout_2.addWidget(self.i5)
        self.l6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l6.setObjectName("l6")
        self.verticalLayout_2.addWidget(self.l6)
        self.i6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i6.setText("")
        self.i6.setObjectName("i6")
        self.verticalLayout_2.addWidget(self.i6)
        self.l7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l7.setObjectName("l7")
        self.verticalLayout_2.addWidget(self.l7)
        self.i7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i7.setText("")
        self.i7.setObjectName("i7")
        self.verticalLayout_2.addWidget(self.i7)
        self.l8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l8.setObjectName("l8")
        self.verticalLayout_2.addWidget(self.l8)
        self.i8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i8.setText("")
        self.i8.setObjectName("i8")
        self.verticalLayout_2.addWidget(self.i8)
        self.l9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l9.setObjectName("l9")
        self.verticalLayout_2.addWidget(self.l9)
        self.i9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i9.setText("")
        self.i9.setObjectName("i9")
        self.verticalLayout_2.addWidget(self.i9)
        self.l10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l10.setObjectName("l10")
        self.verticalLayout_2.addWidget(self.l10)
        self.i10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i10.setText("")
        self.i10.setObjectName("i10")
        self.verticalLayout_2.addWidget(self.i10)
        self.l11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l11.setObjectName("l11")
        self.verticalLayout_2.addWidget(self.l11)
        self.i11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i11.setText("")
        self.i11.setObjectName("i11")
        self.verticalLayout_2.addWidget(self.i11)
        self.l12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l12.setObjectName("l12")
        self.verticalLayout_2.addWidget(self.l12)
        self.i12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i12.setText("")
        self.i12.setObjectName("i12")
        self.verticalLayout_2.addWidget(self.i12)
        self.l13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.l13.setObjectName("l13")
        self.verticalLayout_2.addWidget(self.l13)
        self.i13 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.i13.setText("")
        self.i13.setObjectName("i13")
        self.verticalLayout_2.addWidget(self.i13)
        self.predict = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.predict.setObjectName("predict")
        self.verticalLayout_2.addWidget(self.predict)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(290, 150, 1321, 441))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = MplWidget(self.horizontalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4.addWidget(self.widget)
        self.widget_2 = MplWidget(self.horizontalLayoutWidget_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 910, 241, 49))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.savedHouses = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.savedHouses.setObjectName("savedHouses")
        self.verticalLayout.addWidget(self.savedHouses)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 970, 221, 32))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.load = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.load.setObjectName("load")
        self.horizontalLayout_6.addWidget(self.load)
        self.dele = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.dele.setObjectName("dele")
        self.horizontalLayout_6.addWidget(self.dele)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(1200, 100, 211, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.prediction = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.prediction.setObjectName("prediction")
        self.horizontalLayout_5.addWidget(self.prediction)
        self.widget_3 = MplWidget(self.frame)
        self.widget_3.setGeometry(QtCore.QRect(290, 600, 1321, 421))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(290, 90, 321, 49))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.selectFeature = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.selectFeature.setObjectName("selectFeature")
        self.verticalLayout_3.addWidget(self.selectFeature)
        self.selectFeatureButton = QtWidgets.QPushButton(self.frame)
        self.selectFeatureButton.setGeometry(QtCore.QRect(610, 110, 121, 32))
        self.selectFeatureButton.setObjectName("selectFeatureButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l0.setText(_translate("MainWindow", "Street Address"))
        self.l1.setText(_translate("MainWindow", "Rate of Policing"))
        self.l2.setText(_translate("MainWindow", "land zoned for lots over 25,000 sq.ft"))
        self.l3.setText(_translate("MainWindow", "proportion of non-retail business"))
        self.l4.setText(_translate("MainWindow", "Charles River (1 or 0)"))
        self.l5.setText(_translate("MainWindow", "nitric oxides concentration"))
        self.l6.setText(_translate("MainWindow", "number of rooms"))
        self.l7.setText(_translate("MainWindow", "proportion of units built prior to 1940"))
        self.l8.setText(_translate("MainWindow", "distances to employment centres"))
        self.l9.setText(_translate("MainWindow", "index of accessibility to highways"))
        self.l10.setText(_translate("MainWindow", "property-tax rate per $10,000"))
        self.l11.setText(_translate("MainWindow", "pupil-teacher ratio by town"))
        self.l12.setText(_translate("MainWindow", "1000(Bk - 0.63)^2"))
        self.l13.setText(_translate("MainWindow", "% lower status of the population"))
        self.predict.setText(_translate("MainWindow", "Predict Price"))
        self.label_3.setText(_translate("MainWindow", "Saved House Predictions"))
        self.load.setText(_translate("MainWindow", "Load Data"))
        self.dele.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Predicted Price $"))
        self.prediction.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Select a Feature to Compare"))
        self.selectFeatureButton.setText(_translate("MainWindow", "Select Feature"))

from mplwidget import MplWidget
